import { type ReactNode } from 'react';
import { type LucideIcon } from 'lucide-react';
import {
    ArrowRight,
    Award,
    BadgeCheck,
    BadgePercent,
    Car,
    Check,
    CheckCircle,
    CircleDollarSign,
    Clock,
    Coins,
    Compass,
    CreditCard,
    DollarSign,
    Fuel,
    Gauge,
    Gem,
    Globe,
    Handshake,
    Headphones,
    Heart,
    HeartHandshake,
    Key,
    LifeBuoy,
    Lock,
    Map,
    MapPin,
    MessageSquare,
    Navigation,
    PhoneCall,
    PiggyBank,
    Rocket,
    Route,
    Scan,
    Search,
    Shield,
    ShieldCheck,
    ShieldHalf,
    Smile,
    Snowflake,
    Sparkles,
    Star,
    Sun,
    Tags,
    Target,
    ThumbsUp,
    Timer,
    TrendingUp,
    Trophy,
    Truck,
    Users,
    Wallet,
    Wifi,
    Wind,
    Zap,
} from 'lucide-react';

export const DYNAMIC_ICON_MAP: Record<string, LucideIcon> = {
    ArrowRight,
    Award,
    BadgeCheck,
    BadgePercent,
    Car,
    Check,
    CheckCircle,
    CircleDollarSign,
    Clock,
    Coins,
    Compass,
    CreditCard,
    DollarSign,
    Fuel,
    Gauge,
    Gem,
    Globe,
    Handshake,
    Headphones,
    Heart,
    HeartHandshake,
    Key,
    LifeBuoy,
    Lock,
    Map,
    MapPin,
    MessageSquare,
    Navigation,
    PhoneCall,
    PiggyBank,
    Rocket,
    Route,
    Scan,
    Search,
    Shield,
    ShieldCheck,
    ShieldHalf,
    Smile,
    Snowflake,
    Sparkles,
    Star,
    Sun,
    Tags,
    Target,
    ThumbsUp,
    Timer,
    TrendingUp,
    Trophy,
    Truck,
    Users,
    Wallet,
    Wifi,
    Wind,
    Zap,
};

export const CURIATED_ICONS = [
    { name: 'Shield', label: 'Shield' },
    { name: 'ShieldCheck', label: 'Verified' },
    { name: 'CircleDollarSign', label: 'Best Price' },
    { name: 'CreditCard', label: 'Payment' },
    { name: 'Zap', label: 'Quick' },
    { name: 'MapPin', label: 'Location' },
    { name: 'Headphones', label: 'Support' },
    { name: 'Star', label: 'Quality' },
    { name: 'Car', label: 'Car' },
    { name: 'Heart', label: 'Love' },
    { name: 'HeartHandshake', label: 'Trust' },
    { name: 'CheckCircle', label: 'Guaranteed' },
    { name: 'Sparkles', label: 'Premium' },
    { name: 'Award', label: 'Award' },
    { name: 'ThumbsUp', label: 'Approved' },
    { name: 'Lock', label: 'Secure' },
    { name: 'BadgeCheck', label: 'Verified' },
    { name: 'Rocket', label: 'Fast' },
    { name: 'Timer', label: 'Punctual' },
    { name: 'LifeBuoy', label: 'Help' },
    { name: 'Globe', label: 'Global' },
    { name: 'Trophy', label: 'Best' },
    { name: 'Coins', label: 'Savings' },
    { name: 'PiggyBank', label: 'Savings' },
    { name: 'Target', label: 'Focused' },
    { name: 'Users', label: 'Team' },
    { name: 'Smile', label: 'Happy' },
    { name: 'Sun', label: 'Experience' },
    { name: 'Truck', label: 'Fleet' },
    { name: 'PhoneCall', label: 'Contact' },
    { name: 'MessageSquare', label: 'Chat' },
    { name: 'BadgePercent', label: 'Deals' },
    { name: 'Gem', label: 'Premium' },
    { name: 'Handshake', label: 'Partnership' },
    { name: 'DollarSign', label: 'Money' },
    { name: 'ArrowRight', label: 'Arrow' },
    { name: 'Check', label: 'Check' },
    { name: 'Clock', label: 'Time' },
    { name: 'Compass', label: 'Guide' },
    { name: 'Fuel', label: 'Fuel' },
    { name: 'Gauge', label: 'Speed' },
    { name: 'Key', label: 'Key' },
    { name: 'Map', label: 'Map' },
    { name: 'Navigation', label: 'Navigate' },
    { name: 'Route', label: 'Route' },
    { name: 'Scan', label: 'Scan' },
    { name: 'Search', label: 'Search' },
    { name: 'ShieldHalf', label: 'Insured' },
    { name: 'Snowflake', label: 'AC' },
    { name: 'Tags', label: 'Tags' },
    { name: 'TrendingUp', label: 'Trending' },
    { name: 'Wallet', label: 'Wallet' },
    { name: 'Wifi', label: 'WiFi' },
    { name: 'Wind', label: 'AC' },
];

export function DynamicIcon({
    name,
    className,
    fallback = null,
}: {
    name: string | null;
    className?: string;
    fallback?: ReactNode;
}) {
    if (!name) return fallback;
    if (/^M[\s\d]/.test(name)) {
        return (
            <svg className={className} fill="none" stroke="currentColor" viewBox="0 0 24 24" strokeWidth="1.5">
                <path strokeLinecap="round" strokeLinejoin="round" d={name} />
            </svg>
        );
    }
    const IconComp = DYNAMIC_ICON_MAP[name];
    if (IconComp) return <IconComp className={className} />;
    return fallback;
}
